build:
  stage: build
  image: centos:7
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRVIER: overlay2
  services:
    - docker:dind
  before_script:
    - "yum -y install gettext docker"
  script:
    - "cd $CI_PROJECT_DIR"
    - "docker build -f <(envsubst Dockerfile) -t hello-world ."
