build:
  stage: build
  image: centos:7
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRVIER: overlay2
  services:
    - name: docker:dind
      entrypoint:
        - "/usr/local/bin/dockerd-entrypoint.sh"
        - "--insecure-registry i.am.jds2001.org:5000"
  before_script:
    - "yum -y install gettext docker-client"
  script:
    - "cd $CI_PROJECT_DIR"
    - "envsubst < Dockerfile.template > Dockerfile"
    - "docker build -t hello-world ."
    - "docker tag hello-world i.am.jds2001.org:5000/hello-world:$CI_JOB_ID"
    - "docker tag hello-world i.am.jds2001.org:5000/hello-world:latest"
    - "docker push i.am.jds2001.org:5000/hello-world:$CI_JOB_ID"
    - "docker push i.am.jds2001.org:5000/hello-world:latest"

