build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRVIER: overlay2
  services:
    - docker:dind
  script:
    - "cd $CI_PROJECT_DIR"
    - "docker build -f <(envsubst Dockerfile) -t hello-world .'
